services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Bangkok
      - USER=${USER_NAME}
      - PASS=${USER_PASS}
    volumes:
      - ./transmission/config:/config
      - /media/usb/downloads:/data/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
